Repository brstu/TMAU-2024, pull requests merged in 2024-12, with the labels that each got.

#226 [task_02] Add solution
  readme.md
  trunk/as0006442/src/CMakeLists.txt
  trunk/as0006442/task_01/doc/readme.md
  trunk/as0006442/task_01/src/CMakeLists.txt
  trunk/as0006442/task_01/src/main.cpp
  trunk/as0006442/task_02/doc/doxygen.md
  trunk/as0006442/task_02/doc/readme.md
  trunk/as0006442/task_02/src/CMakeLists.txt
  trunk/as0006442/task_02/src/main.cpp
Labels: AS-64

#231 [task_04] Add Solution
  readme.md
  trunk/as0006409/task_04/doc/images/result.png
  trunk/as0006409/task_04/doc/readme.md
  trunk/as0006409/task_04/readme.md
Labels: AS-64

#235 [task_03] Add solution
  readme.md
  trunk/as0006442/task_03/doc/readme.md
  trunk/as0006442/task_03/image/connect.png
  trunk/as0006442/task_03/image/endlab.png
  trunk/as0006442/task_03/image/hello_PLC.png
  trunk/as0006442/task_03/image/ip.png
  trunk/as0006442/task_03/image/login.png
  trunk/as0006442/task_03/image/password.png
Labels: AS-64

#237 [task_03] Add solution
  readme.md
  trunk/as0006416/task_03/doc/readme.md
  trunk/as0006416/task_03/images/connect.png
  trunk/as0006416/task_03/images/end.png
  trunk/as0006416/task_03/images/hello_PLC.png
  trunk/as0006416/task_03/images/ip.png
  trunk/as0006416/task_03/images/login.png
  trunk/as0006416/task_03/images/password.png
Labels: AS-64

#238 [task_04] Add solution
  readme.md
  trunk/as0006416/task_04/images/connect.png
  trunk/as0006416/task_04/readme.md
Labels: AS-64

#236 [task_04] Add solution
  readme.md
  trunk/as0006442/task_04/image/connect.png
  trunk/as0006442/task_04/readme.md
Labels: AS-64

#232 [task_05] Add Solution
  readme.md
  trunk/as0006409/task_05/doc/images/monitor.png
  trunk/as0006409/task_05/doc/readme.md
Labels: AS-64

#239 [task_05] Add solution
  trunk/as0006442/task_05/image/lab5.PNG
  trunk/as0006442/task_05/readme.md
Labels: AS-64

#249 [task_01] Add task
  readme.md
  trunk/as0006402/task_01/doc/README.md
  trunk/as0006402/task_01/src/CMakeLists.txt
  trunk/as0006402/task_01/src/main.cpp
Labels: AS-64

#244 [task_04] Add solution
  readme.md
  trunk/as0006319/task_04/doc/readme.md
  trunk/as0006319/task_04/img/PLCnext.png
  trunk/as0006319/task_04/img/file.png
  trunk/as0006319/task_04/img/output.png
  trunk/as0006319/task_04/img/sdk.png
Labels: AS-63

#258 [task_03] Task03
  readme.md
  trunk/as0006402/task_03/doc/readme.md
  trunk/as0006402/task_03/images/photo_of_controler.jpg
  trunk/as0006402/task_03/images/pravo_i_levo.jpg
  trunk/as0006402/task_03/images/rezultat.jpg
  trunk/as0006402/task_03/images/win_cp.jpg
Labels: AS-64

#257 [task_02] Add content
  readme.md
  trunk/as0006402/task_02/doc/doxygen.md
  trunk/as0006402/task_02/doc/readme.md
  trunk/as0006402/task_02/doc/results.txt
  trunk/as0006402/task_02/images/Linear_model.png
  trunk/as0006402/task_02/images/Nonlinear_model.png
  trunk/as0006402/task_02/src/CMakeLists.txt
  trunk/as0006402/task_02/src/novaualaba2.cpp
Labels: AS-64

#253 [task_03] Add solution
  trunk/as000220021/task_02/doc/doxygen.md
  trunk/as000220021/task_02/doc/readme.md
  trunk/as000220021/task_02/images/Linear_model.png
  trunk/as000220021/task_02/images/Nonlinear_model.png
  trunk/as000220021/task_02/src/CMakeLists.txt
  trunk/as000220021/task_02/src/main.cpp
  trunk/as000220021/task_03/doc/readme.md
  trunk/as000220021/task_03/images/check_connection.jpg
  trunk/as000220021/task_03/images/file.jpg
  trunk/as000220021/task_03/images/ip.png
  trunk/as000220021/task_03/images/putty.png
  trunk/as000220021/task_03/images/putty_login.jpg
  trunk/as000220021/task_03/images/result.png
  trunk/as000220021/task_03/images/winSCP_log.jpg
Labels: help wanted, AS-63

#263 [task_03] Add task
  readme.md
  trunk/as0006414/task_03/doc/README.md
  trunk/as0006414/task_03/doc/img/1.png
  trunk/as0006414/task_03/doc/img/2.png
  trunk/as0006414/task_03/doc/img/3.png
  trunk/as0006414/task_03/doc/img/4.png
  trunk/as0006414/task_03/doc/img/5.png
Labels: AS-64

#264 [task_04] Add task
  readme.md
  trunk/as0006414/task_04/doc/README.md
  trunk/as0006414/task_04/doc/img/1.png
  trunk/as0006414/task_04/doc/img/2.png
Labels: AS-64

#243 [task_04] Add Solution
  readme.md
  trunk/as0006404/task_04/doc/img/res.png
  trunk/as0006404/task_04/doc/readme.md
Labels: AS-64

#272 [task_05] Add solution
  readme.md
Labels: AS-64

#169 [task_02] Add Solution
  trunk/as0006416/task_02/doc/doxygen.md
  trunk/as0006416/task_02/img/Linea.png
  trunk/as0006416/task_02/readme.md
  trunk/as0006416/task_02/src/CMakeLists.txt
  trunk/as0006416/task_02/src/ConsoleApplication1.cpp
Labels: AS-64

#271 [task_05] Add solution
  readme.md
  trunk/as0006413/task_05/doc/readme.md
  trunk/as0006413/task_05/img/doned.png
Labels: AS-64

#251 [task_03] Add solution
  trunk/as0006307/doc/images/PuTTY_conect.png
  trunk/as0006307/doc/images/PuTTY_log_pass.png
  trunk/as0006307/doc/images/WinCP_conect.png
  trunk/as0006307/doc/images/conect.png
  trunk/as0006307/doc/images/hi_PLCnext_settings.png
  trunk/as0006307/doc/images/network_conf.png
  trunk/as0006307/doc/images/result.png
  trunk/as0006307/doc/readme.md
Labels: AS-63

#256 [task_02] Add solution
  trunk/as0006312/task_02/doc/doxygen.md
  trunk/as0006312/task_02/doc/readme.md
  trunk/as0006312/task_02/images/Linear_model.png
  trunk/as0006312/task_02/images/Nonlinear_model.png
  trunk/as0006312/task_02/src/CMakeLists.txt
  trunk/as0006312/task_02/src/main.cpp
Labels: AS-63

#260 [task_03] Added task_03
  readme.md
  trunk/as0006308/task_03/doc/readme.md
  trunk/as0006308/task_03/img/chekConect.png
  trunk/as0006308/task_03/img/conect.png
  trunk/as0006308/task_03/img/file.png
  trunk/as0006308/task_03/img/log.png
  trunk/as0006308/task_03/img/scp.png
  trunk/as0006308/task_03/img/work.png
Labels: AS-63

#261 [task_04] Added task_04
  readme.md
  trunk/as0006308/task_04/doc/readme.md
  trunk/as0006308/task_04/img/proekt.png
  trunk/as0006308/task_04/img/sborka.png
  trunk/as0006308/task_04/img/work.png
Labels: AS-63

#274 [task_03] Add solution
  readme.md
  trunk/as0006305/task_03/doc/images/PuTTY_connect.png
  trunk/as0006305/task_03/doc/images/PuTTY_login_password.png
  trunk/as0006305/task_03/doc/images/WinCP_connect.png
  trunk/as0006305/task_03/doc/images/connect.png
  trunk/as0006305/task_03/doc/images/hello_PLCnext_settings.png
  trunk/as0006305/task_03/doc/images/network_configuration.png
  trunk/as0006305/task_03/doc/readme.md
Labels: AS-63

#252 [task_04] Add solution
  trunk/as0006307/task04/doc/images/results.png
  trunk/as0006307/task04/doc/readme.md
Labels: AS-63, Not marked in the table

#287 [task_05] Add Task
  readme.md
  trunk/as64220038/task_05/doc/readme.md
Labels: AS-64

#262 [task_04] Added task_04
  readme.md
  trunk/as0006323/task_04/images/lab1.png
  trunk/as0006323/task_04/images/lab2.png
  trunk/as0006323/task_04/readme.md
Labels: AS-63

#273 [task_04] Add solution
  trunk/as0006306/task04/doc/images/result.png
  trunk/as0006306/task04/doc/readme.md
Labels: AS-63

#276 [task_04] New task done
  readme.md
  trunk/as0006305/task_04/doc/images/result.png
  trunk/as0006305/task_04/doc/readme.md
Labels: AS-63

#280 [task_02] Add solution
  readme.md
  trunk/as0006303/task_02/doc/doxygen.md
  trunk/as0006303/task_02/doc/readme.md
  trunk/as0006303/task_02/images/Linear_model.png
  trunk/as0006303/task_02/images/Nonlinear_model.png
  trunk/as0006303/task_02/src/CMakeLists.txt
  trunk/as0006303/task_02/src/main.cpp
Labels: AS-63

#282 [task_05] Add solution
  readme.md
  trunk/as0006316/task5/doc/readme.md
  trunk/as0006316/task5/img/monitor_done.png
Labels: AS-63

#283 [task_03] Add solution
  trunk/as0006303/task_03/doc/images/Снимок экрана 1.png
  trunk/as0006303/task_03/doc/images/Снимок экрана 2.png
  trunk/as0006303/task_03/doc/images/Снимок экрана 3.png
  trunk/as0006303/task_03/doc/images/Снимок экрана 4.png
  trunk/as0006303/task_03/doc/images/Снимок экрана 5.png
  trunk/as0006303/task_03/doc/images/Снимок экрана 6.png
  trunk/as0006303/task_03/doc/images/Снимок экрана 7.png
  trunk/as0006303/task_03/doc/images/Снимок экрана 8.jpeg
  trunk/as0006303/task_03/doc/images/Снимок экрана 9.png
  trunk/as0006303/task_03/doc/readme.md
Labels: AS-63

#285 [task_04] Add solution
  trunk/as0006303/task_04/doc/images/PLCnext.png
  trunk/as0006303/task_04/doc/images/laboratory.jpg
  trunk/as0006303/task_04/doc/images/res.png
  trunk/as0006303/task_04/doc/readme.md
Labels: AS-63

#278 [task_04] Add solution
  trunk/as000220021/task_04/doc/images/result.png
  trunk/as000220021/task_04/doc/readme.md
Labels: bug, AS-63

#279 [task_05] Add solution
  trunk/as000220021/task_05/doc/readme.md
  trunk/as000220021/task_05/img/monitor_done.png
Labels: bug, AS-63

#289 [task_05] Add solution
  trunk/as0006307/task_05/doc/readme.md
  trunk/as0006307/task_05/img/monitor_done.png
Labels: AS-63, Not marked in the table

#288 [task_03] Add solution
  trunk/as0006307/doc/readme.md
  trunk/as0006307/task_03/doc/images/PuTTY_conect.png
  trunk/as0006307/task_03/doc/images/PuTTY_log_pass.png
  trunk/as0006307/task_03/doc/images/WinCP_conect.png
  trunk/as0006307/task_03/doc/images/conect.png
  trunk/as0006307/task_03/doc/images/hi_PLCnext_settings.png
  trunk/as0006307/task_03/doc/images/network_conf.png
  trunk/as0006307/task_03/doc/images/result.png
  trunk/as0006307/task_03/doc/readme.md
Labels: AS-63
