Repository brstu/TMAU-2024, pull requests merged in 2024-11, with the labels that each got.

#99 [task_03] Add Solution
  readme.md
  trunk/as64220038/task_03/doc/images/1.jpg
  trunk/as64220038/task_03/doc/images/2.jpg
  trunk/as64220038/task_03/doc/images/3.jpg
  trunk/as64220038/task_03/doc/images/4.jpg
  trunk/as64220038/task_03/doc/images/5.jpg
  trunk/as64220038/task_03/doc/images/6.jpg
  trunk/as64220038/task_03/doc/images/7.jpg
  trunk/as64220038/task_03/doc/images/8.jpg
  trunk/as64220038/task_03/doc/images/9.jpg
  trunk/as64220038/task_03/doc/readme.md
Labels: AS-64

#101 [task_04] Add task
  readme.md
  trunk/as64220038/task_04/doc/images/1.png
  trunk/as64220038/task_04/doc/images/2.jpg
  trunk/as64220038/task_04/doc/images/3.jpg
  trunk/as64220038/task_04/doc/readme.md
Labels: AS-64

#113 [task_02] Add solution
  readme.md
  trunk/as0006413/task_02/doc/doxygen.md
  trunk/as0006413/task_02/doc/readme.md
  trunk/as0006413/task_02/images/linear.png
  trunk/as0006413/task_02/images/nonlinear.png
  trunk/as0006413/task_02/src/CMakeLists.txt
  trunk/as0006413/task_02/src/main.cpp
Labels: AS-64

#114 [task_03] Add solution
  readme.md
  trunk/as0006413/task_03/doc/readme.md
  trunk/as0006413/task_03/images/PuTTY_login_pass.png
  trunk/as0006413/task_03/images/WinCP_conn.png
  trunk/as0006413/task_03/images/create_connect.png
  trunk/as0006413/task_03/images/create_hello_PLCnext_settings.png
  trunk/as0006413/task_03/images/network_config.png
  trunk/as0006413/task_03/images/res.png
  trunk/as0006413/task_03/images/up PuTTY_connect.png
Labels: AS-64

#89 [task_02] Lab2
  trunk/as0006325/task_03/doc/readme.md
  trunk/as0006424/task_02/doc/doxygen.md
  trunk/as0006424/task_02/doc/readme.md
  trunk/as0006424/task_02/images/linearmodel.PNG
  trunk/as0006424/task_02/images/nonlinearmodel.PNG
  trunk/as0006424/task_02/src/CMakeLists.txt
  trunk/as0006424/task_02/src/Git2.cpp
Labels: invalid, AS-64, Not marked in the table

#96 [task_01] Add task content
  readme.md
  trunk/as0006404/task_01/doc/readme.md
  trunk/as0006404/task_01/src/CMakeLists.txt
  trunk/as0006404/task_01/src/main.cpp
Labels: AS-64

#97 [task_01] Add content
  readme.md
  trunk/as0006433/task_01/doc/readme.md
  trunk/as0006433/task_01/src/CMakeLists.txt
  trunk/as0006433/task_01/src/main.cpp
Labels: AS-64

#105 [task_01] Add task_01
  trunk/as0006443/task_01/doc/README.md
  trunk/as0006443/task_01/src/CMakeLists.txt
  trunk/as0006443/task_01/src/main.cpp
Labels: AS-64

#112 [task_03] Add solution
  readme.md
  trunk/as0006312/task_03/doc/readme.md
  trunk/as0006312/task_03/images/check_connection.jpg
  trunk/as0006312/task_03/images/file.jpg
  trunk/as0006312/task_03/images/ip.png
  trunk/as0006312/task_03/images/putty.png
  trunk/as0006312/task_03/images/putty_login.jpg
  trunk/as0006312/task_03/images/result.png
  trunk/as0006312/task_03/images/winSCP_log.jpg
  trunk/as0006409/task_02/doc/readme.md
Labels: AS-64

#103 [task_04] Add task
  readme.md
  trunk/as0006322/task_01/doc/readme.md
  trunk/as0006322/task_01/src/CMakeLists.txt
  trunk/as0006322/task_01/src/main.cpp
  trunk/as0006322/task_02/doc/doxygen.md
  trunk/as0006322/task_02/doc/readme.md
  trunk/as0006322/task_02/doc/results.txt
  trunk/as0006322/task_02/images/5269634313815713984.jpg
  trunk/as0006322/task_02/src/CMakeLists.txt
  trunk/as0006322/task_02/src/task2.cpp
  trunk/as0006322/task_03/doc/readme.md
  trunk/as0006322/task_03/images/check_connection.jpg
  trunk/as0006322/task_03/images/file.jpg
  trunk/as0006322/task_03/images/ip.png
  trunk/as0006322/task_03/images/putty.png
  trunk/as0006322/task_03/images/putty_login.jpg
  trunk/as0006322/task_03/images/result.png
  trunk/as0006322/task_03/images/winSCP_log.jpg
  trunk/as0006322/task_04/doc/readme.md
  trunk/as0006322/task_04/img/PLCnext.png
  trunk/as0006322/task_04/img/file.png
  trunk/as0006322/task_04/img/output.png
  trunk/as0006322/task_04/img/sdk.png
Labels: AS-63

#107 [task_02] Add solution
  readme.md
  trunk/as0006302/task_02/.gitkeep
  trunk/as0006302/task_02/doc/doxygen.md
  trunk/as0006302/task_02/doc/readme.md
  trunk/as0006302/task_02/images/Linear_model.png
  trunk/as0006302/task_02/images/Nonlinear_model.png
  trunk/as0006302/task_02/src/CMakeLists.txt
  trunk/as0006302/task_02/src/main.cpp
Labels: AS-63

#109 [task_03] Add solution
  readme.md
  trunk/as0006302/task_02/doc/readme.md
  trunk/as0006302/task_03/doc/images/Снимок экрана 1.png
  trunk/as0006302/task_03/doc/images/Снимок экрана 2.png
  trunk/as0006302/task_03/doc/images/Снимок экрана 3.png
  trunk/as0006302/task_03/doc/images/Снимок экрана 4.png
  trunk/as0006302/task_03/doc/images/Снимок экрана 5.png
  trunk/as0006302/task_03/doc/images/Снимок экрана 6.png
  trunk/as0006302/task_03/doc/images/Снимок экрана 7.png
  trunk/as0006302/task_03/doc/images/Снимок экрана 8.jpeg
  trunk/as0006302/task_03/doc/images/Снимок экрана 9.png
  trunk/as0006302/task_03/doc/readme.md
Labels: AS-63

#118 [task_04] Add solution
  readme.md
  trunk/as0006302/task_03/doc/readme.md
  trunk/as0006302/task_04/doc/images/PLCnext.png
  trunk/as0006302/task_04/doc/images/laboratory.jpg
  trunk/as0006302/task_04/doc/images/res.png
  trunk/as0006302/task_04/doc/readme.md
Labels: AS-63

#119 [task_05] Add solution
  readme.md
  trunk/as0006302/task_03/doc/readme.md
  trunk/as0006302/task_05/doc/image/monitor_done.png
  trunk/as0006302/task_05/doc/readme.md
Labels: AS-63

#95 [task_05] Add solution
  trunk/as0006325/task_05/doc/images/dbeditor_settings.png
  trunk/as0006325/task_05/doc/images/easyserver_settings.png
  trunk/as0006325/task_05/doc/readme.md
Labels: AS-63, Not marked in the table

#122 [task_06] Add solution
  readme.md
  trunk/as0006325/task_06/doc/readme.md
Labels: AS-63

#111 [task_02] Add solution
  readme.md
  trunk/as0006326/task_02/doc/Readme.md
  trunk/as0006326/task_02/doc/doxygen.md
  trunk/as0006326/task_02/images/NonMod.png
  trunk/as0006326/task_02/images/linMod.png
  trunk/as0006326/task_02/src/CMakeLists.txt
  trunk/as0006326/task_02/src/main.cpp
Labels: AS-63

#88 [task_02] Add solution
  readme.md
  trunk/as0006314/task_02/doc/doxygen.md
  trunk/as0006314/task_02/doc/readme.md
  trunk/as0006314/task_02/src/CMakeLists.txt
  trunk/as0006314/task_02/src/main.cpp
Labels: AS-63

#84 [task_03] Add solution
  readme.md
  trunk/as0006311/task_03/doc/images/WinCP_connect.png
  trunk/as0006311/task_03/doc/images/hello_PLCnext_настройки.png
  trunk/as0006311/task_03/doc/images/Сеть.png
  trunk/as0006311/task_03/doc/images/пароль_для_входа.png
  trunk/as0006311/task_03/doc/images/пароль_для_входа_в_систему.png
  trunk/as0006311/task_03/doc/images/подключение.png
  trunk/as0006311/task_03/doc/images/результат.jpg
  trunk/as0006311/task_03/doc/readme.md
Labels: AS-63, Not marked in the table

#115 [task_03] Add solution
  readme.md
  trunk/as0006326/task_02/src/CMakeLists.txt
  trunk/as0006326/task_02/src/main.cpp
  trunk/as0006326/task_03/doc/images/img1.png
  trunk/as0006326/task_03/doc/images/img2.png
  trunk/as0006326/task_03/doc/images/img3.png
  trunk/as0006326/task_03/doc/images/img4.png
  trunk/as0006326/task_03/doc/images/img5.png
  trunk/as0006326/task_03/doc/images/img6.png
  trunk/as0006326/task_03/doc/images/img7.png
  trunk/as0006326/task_03/doc/images/img8.png
  trunk/as0006326/task_03/doc/images/img9.png
  trunk/as0006326/task_03/doc/readme.md
Labels: AS-63

#117 [task_04] Add solution
  readme.md
  trunk/as0006326/task_02/src/CMakeLists.txt
  trunk/as0006326/task_04/doc/images/PLC.png
  trunk/as0006326/task_04/doc/images/lab.jpg
  trunk/as0006326/task_04/doc/images/result.png
  trunk/as0006326/task_04/doc/readme.md
Labels: AS-63

#78 [task_01] Add solution
  readme.md
  trunk/as0006319/task_01/doc/readme.md
  trunk/as0006319/task_01/src/CMakeLists.txt
  trunk/as0006319/task_01/src/main.cpp
Labels: AS-63, Not marked in the table

#120 [task_04] Add solution
  readme.md
  trunk/as0006311/task_04/doc/images/result.png
  trunk/as0006311/task_04/doc/readme.md
Labels: AS-63

#80 [task_04] Add solution
  readme.md
  trunk/as0006309/task_03/doc/images/result.png
  trunk/as0006309/task_04/doc/images/result.png
  trunk/as0006309/task_04/doc/readme.md
Labels: AS-63

#92 [task_04] Add solution
  readme.md
  trunk/as0006314/task_02/src/CMakeLists.txt
  trunk/as0006314/task_03/doc/readme.md
  trunk/as0006314/task_03/images/check_connection.jpg
  trunk/as0006314/task_03/images/file.jpg
  trunk/as0006314/task_03/images/ip.png
  trunk/as0006314/task_03/images/putty.png
  trunk/as0006314/task_03/images/putty_login.jpg
  trunk/as0006314/task_03/images/result.png
  trunk/as0006314/task_03/images/winSCP_log.jpg
  trunk/as0006314/task_04/doc/readme.md
  trunk/as0006314/task_04/img/file.png
  trunk/as0006314/task_04/img/output.png
Labels: AS-63

#93 [task_05] Add solution
  readme.md
  trunk/as0006314/task_05/doc/readme.md
  trunk/as0006314/task_05/img/monitor.png
Labels: AS-63

#98 [task_06] Add solution
  readme.md
  trunk/as0006314/task_06/doc/readme.md
Labels: AS-63

#123 [task_05] Add solution
  readme.md
  trunk/as0006311/task_05/doc/readme.md
  trunk/as0006311/task_05/img/monitor_done.png
Labels: AS-63

#121 [task_05] Add solution
  readme.md
  trunk/as0006309/task_05/doc/readme.md
  trunk/as0006309/task_05/img/monitor_done.png
Labels: AS-63

#125 [task_06] Add solution
  readme.md
  trunk/as0006311/task_06/doc/readme.md
Labels: AS-63

#124 [task_06] Add solution
  readme.md
  trunk/as0006309/task_06/doc/readme.md
Labels: AS-63

#61 [task_01] Add solution
  readme.md
  trunk/as0006320/task_01/doc/readme.md
  trunk/as0006320/task_01/src/CMakeLists.txt
  trunk/as0006320/task_01/src/lab1.cpp
Labels: AS-63

#133 [task_04] Add Solution
  readme.md
  trunk/as0006409/task_04/img/connect.png
  trunk/as0006409/task_04/readme.md
Labels: AS-64

#130 [task_03] Add Solution
  readme.md
  trunk/as0006407/task_03/doc/readme.md
  trunk/as0006407/task_03/img/connect.png
  trunk/as0006407/task_03/img/end.png
  trunk/as0006407/task_03/img/hello_PLC.png
  trunk/as0006407/task_03/img/ip.png
  trunk/as0006407/task_03/img/login.png
  trunk/as0006407/task_03/img/password.png
Labels: AS-64

#147 [task_03] Add solution
  readme.md
  trunk/as0006404/task_03/doc/readme.md
  trunk/as0006404/task_03/images/1.png
  trunk/as0006404/task_03/images/2.png
  trunk/as0006404/task_03/images/3.png
  trunk/as0006404/task_03/images/4.png
  trunk/as0006404/task_03/images/5.png
  trunk/as0006404/task_03/images/connect.png
  trunk/as0006404/task_03/images/result.png
Labels: AS-64

#134 [task_04] Add solution
  readme.md
  trunk/as0006413/task_04/doc/readme.md
  trunk/as0006413/task_04/img/file_property.png
  trunk/as0006413/task_04/img/output_c.png
Labels: AS-64

#180 [task_04] Lab4
  readme.md
  trunk/as0006424/task_04/doc/images/controller_result.png
  trunk/as0006424/task_04/doc/readme.md
Labels: AS-64

#160 [task_01] Add task 01
  readme.md
  trunk/as0006444/task_01/doc/readme.md
  trunk/as0006444/task_01/src/CMakeLists.txt
  trunk/as0006444/task_01/src/main.cpp
Labels: AS-64

#168 [task_01] Add Solution
  readme.md
  trunk/as0006416/task_01/readme.md
  trunk/as0006416/task_01/src/CMakeLists.txt
  trunk/as0006416/task_01/src/ConsoleApplication1.cpp
Labels: AS-64

#174 [task_02] Done task_02
  readme.md
  trunk/as0006426/task_02/doc/Nonlinear.png
  trunk/as0006426/task_02/doc/doxygen.md
  trunk/as0006426/task_02/doc/linear.png
  trunk/as0006426/task_02/doc/readme.md
  trunk/as0006426/task_02/doc/results.txt
  trunk/as0006426/task_02/src/CMakeLists.txt
  trunk/as0006426/task_02/src/lab2.cpp
Labels: AS-64

#136 [task_02] Add solution
  trunk/as0006316/task2/doc/doxygen.md
  trunk/as0006316/task2/doc/readme.md
  trunk/as0006316/task2/src/CMakeLists.txt
  trunk/as0006316/task2/src/lab2_ef.cpp
Labels: AS-63

#135 [task_01] Add solution
  trunk/as0006316/task1/doc/readme.md
  trunk/as0006316/task1/scr/CMakeLists.txt
  trunk/as0006316/task1/scr/laba1_ef.cpp
Labels: AS-63

#165 [task_01] Added task 1
  readme.md
  trunk/as0006308/task_01/doc/readme.md
  trunk/as0006308/task_01/src/CMakeLists.txt
  trunk/as0006308/task_01/src/task1.cpp
Labels: AS-63

#159 [task_01] Added task_01
  readme.md
  trunk/as0006323/task_01/doc/pic1.png
  trunk/as0006323/task_01/doc/readme.md
  trunk/as0006323/task_01/src/CMakeLists.txt
  trunk/as0006323/task_01/src/ConsoleApplication1.cpp
Labels: AS-63

#176 [task_01] Add task 01
  readme.md
  trunk/as0006313/task_01/doc/readme.md
  trunk/as0006313/task_01/src/CMakeLists.txt
  trunk/as0006313/task_01/src/task_01.cpp
Labels: AS-63

#177 [task_02] Add task_02
  trunk/as0006313/task_02/doc/doxygen.md
  trunk/as0006313/task_02/doc/images/01.png
  trunk/as0006313/task_02/doc/images/02.png
  trunk/as0006313/task_02/doc/readme.md
  trunk/as0006313/task_02/src/CMakeLists.txt
  trunk/as0006313/task_02/src/task_02.cpp
Labels: AS-63

#128 [task_02] Add task
  readme.md
  trunk/as0006443/task_02/doc/images/1.png
  trunk/as0006443/task_02/doc/images/2.png
  trunk/as0006443/task_02/doc/moxygen.md
  trunk/as0006443/task_02/doc/readme.md
  trunk/as0006443/task_02/src/CMakeLists.txt
  trunk/as0006443/task_02/src/main.cpp
Labels: AS-64

#152 [task_04] Add solution
  readme.md
  trunk/as0006316/task_04/doc/readme.md
  trunk/as0006316/task_04/images/output.png
Labels: AS-63

#151 [task_03] Added solution
  trunk/as0006316/task_03/doc/readme.md
  trunk/as0006316/task_03/images/PuTTY_connection.png
  trunk/as0006316/task_03/images/PuTTY_log_in.png
  trunk/as0006316/task_03/images/WinCP_connection.jpg
  trunk/as0006316/task_03/images/connection.png
  trunk/as0006316/task_03/images/controller_configuration.png
  trunk/as0006316/task_03/images/hello_PLCnext_settings.png
  trunk/as0006316/task_03/images/hello_message.jpg
Labels: AS-63

#161 [task_02] Added task_02
  readme.md
  trunk/as0006323/task_02/doc/README.md
  trunk/as0006323/task_02/doc/docs.md
  trunk/as0006323/task_02/img/linear.png
  trunk/as0006323/task_02/img/nonlinear.png
  trunk/as0006323/task_02/src/CMakeLists.txt
  trunk/as0006323/task_02/src/results.txt
  trunk/as0006323/task_02/src/solution.cpp
Labels: AS-63

#162 [task_01] Add task01
  readme.md
  trunk/as0006417/task_01/doc/readme.md
  trunk/as0006417/task_01/src/CMakeLists.txt
  trunk/as0006417/task_01/src/Source.cpp
Labels: AS-64

#163 [task_03] Added task_03
  readme.md
  trunk/as0006323/task_03/doc/images/add_executable.jpg
  trunk/as0006323/task_03/doc/images/binary_file.jpg
  trunk/as0006323/task_03/doc/images/check_connection.jpg
  trunk/as0006323/task_03/doc/images/connect.jpg
  trunk/as0006323/task_03/doc/images/connectionIP.jpg
  trunk/as0006323/task_03/doc/images/proof_screenshot.png
  trunk/as0006323/task_03/doc/images/putty_connect.jpg
  trunk/as0006323/task_03/doc/images/putty_login.jpg
  trunk/as0006323/task_03/doc/images/winSCP.jpg
  trunk/as0006323/task_03/doc/images/winSCP_log.jpg
  trunk/as0006323/task_03/doc/readme.md
Labels: AS-63

#166 [task_02] Added task 2
  readme.md
  trunk/as0006308/task_02/doc/doxygen.md
  trunk/as0006308/task_02/doc/images/Linea.jpg
  trunk/as0006308/task_02/doc/readme.md
  trunk/as0006308/task_02/doc/results.txt
  trunk/as0006308/task_02/src/CMakeLists.txt
  trunk/as0006308/task_02/src/main.cpp
Labels: AS-63

#167 [task_01] Add Solution
  readme.md
  trunk/as0006405/task_01/readme.md
  trunk/as0006405/task_01/src/CMakeLists.txt
  trunk/as0006405/task_01/src/Source.cpp
Labels: AS-64

#170 [task_02] Add Solution
  trunk/as0006405/task_02/doc/doxygendoc.md
  trunk/as0006405/task_02/img/linear.png
  trunk/as0006405/task_02/img/nonLinear.png
  trunk/as0006405/task_02/readme.md
  trunk/as0006405/task_02/src/CMakeLists.txt
  trunk/as0006405/task_02/src/Source.cpp
Labels: AS-64

#173 [task_01] Done task_01
  readme.md
  trunk/as0006426/task_01/doc/readme.md
  trunk/as0006426/task_01/src/CMakeLists.txt
  trunk/as0006426/task_01/src/main.cpp
Labels: AS-64

#175 [task_01] Add solution
  readme.md
  trunk/as0006306/task01/doc/readme.md
  trunk/as0006306/task01/src/CMakeLists.txt
  trunk/as0006306/task01/src/main.cpp
Labels: AS-63

#178 [task_03] Add task_03
  readme.md
  trunk/as0006426/task_03/images/Lab3result.png
  trunk/as0006426/task_03/images/Work_together.png
  trunk/as0006426/task_03/images/connect.png
  trunk/as0006426/task_03/images/connect2.png
  trunk/as0006426/task_03/images/login.png
  trunk/as0006426/task_03/images/network.png
  trunk/as0006426/task_03/images/settings.png
  trunk/as0006426/task_03/readme.md
Labels: AS-64

#191 [task_04] Update
  readme.md
  trunk/as0006407/task_02/doc/doxygen.md
  trunk/as0006407/task_02/img/lin.PNG
  trunk/as0006407/task_02/img/nolin.PNG
  trunk/as0006407/task_02/readme.md
  trunk/as0006407/task_02/src/CMakeLists.txt
  trunk/as0006407/task_02/src/lab_2.cpp
  trunk/as0006407/task_04/img/connect.png
  trunk/as0006407/task_04/readme.md
Labels: AS-64

#192 [task_01] Add solution
  readme.md
  trunk/as0006307/task_01/doc/readme.md
  trunk/as0006307/task_01/src/CMakeLists.txt
  trunk/as0006307/task_01/src/Source.cpp
Labels: AS-63

#193 [task_02] Add solution
  readme.md
  trunk/as0006307/task_02/doc/doxygen.md
  trunk/as0006307/task_02/doc/readme.md
  trunk/as0006307/task_02/doc/results.txt
  trunk/as0006307/task_02/src/CMakeLists.txt
  trunk/as0006307/task_02/src/Source.cpp
Labels: AS-63

#188 [task_02] Added task 02
  trunk/as0006320/task_02/doc/doxygendoc.md
  trunk/as0006320/task_02/doc/readme.md
  trunk/as0006320/task_02/images/console_output.png
  trunk/as0006320/task_02/images/inear_model.png
  trunk/as0006320/task_02/images/nonlinear_model.png
  trunk/as0006320/task_02/src/CMakeLists.txt
  trunk/as0006320/task_02/src/main.cpp
Labels: AS-63

#194 [task_02] Add Solution
  readme.md
  trunk/as0006409/task_02/doc/doxygen.md
  trunk/as0006409/task_02/doc/linear.png
  trunk/as0006409/task_02/doc/nonlinear.png
  trunk/as0006409/task_02/doc/readme.md
  trunk/as0006409/task_02/images/linear.png
  trunk/as0006409/task_02/images/nonlinear.png
  trunk/as0006409/task_02/src/CMakeLists.txt
  trunk/as0006409/task_02/src/main.cpp
Labels: AS-64

#200 [task_03] Add third task
  readme.md
  trunk/as0006443/task_03/doc/img/1.png
  trunk/as0006443/task_03/doc/img/2.png
  trunk/as0006443/task_03/doc/img/3.png
  trunk/as0006443/task_03/doc/img/4.png
  trunk/as0006443/task_03/doc/img/5.png
  trunk/as0006443/task_03/doc/img/6.png
  trunk/as0006443/task_03/doc/img/7.png
  trunk/as0006443/task_03/doc/readme.md
Labels: AS-64

#201 [task_01] Add content
  readme.md
  trunk/as0006414/task_01/doc/README.md
  trunk/as0006414/task_01/src/CMakeLists.txt
  trunk/as0006414/task_01/src/main.cpp
Labels: AS-64

#202 [task_02] Add solution
  readme.md
  trunk/as0006306/task02/doc/doxygen.md
  trunk/as0006306/task02/doc/readme.md
  trunk/as0006306/task02/images/Linear_model.png
  trunk/as0006306/task02/images/Nonlinear_model.png
  trunk/as0006306/task02/src/CMakeLists.txt
  trunk/as0006306/task02/src/main.cpp
Labels: AS-63

#203 [task_04] Add task 4
  readme.md
  trunk/as0006320/task_04/doc/readme.md
  trunk/as0006320/task_04/images/console-full-screen.png
  trunk/as0006320/task_04/images/console.png
Labels: AS-63

#206 [task_01] Add task 01
  readme.md
  trunk/as0006304/task_01/doc/README.md
  trunk/as0006304/task_01/src/CMakeLists.txt
  trunk/as0006304/task_01/src/lab.cpp
Labels: AS-63

#209 [task_03] Add solution
  readme.md
  trunk/as0006306/task03/doc/images/PuTTY_connect.png
  trunk/as0006306/task03/doc/images/PuTTY_login_password.png
  trunk/as0006306/task03/doc/images/WinCP_connect.png
  trunk/as0006306/task03/doc/images/connect.png
  trunk/as0006306/task03/doc/images/hello_PLCnext_settings.png
  trunk/as0006306/task03/doc/images/network_configuration.png
  trunk/as0006306/task03/doc/images/result.png
  trunk/as0006306/task03/doc/readme.md
Labels: AS-63

#207 [task_04] Add task_04
  readme.md
  trunk/as0006443/task_04/doc/img/1.png
  trunk/as0006443/task_04/doc/img/2.png
  trunk/as0006443/task_04/doc/readme.md
Labels: AS-64

#210 [task_04] Add task_04
  readme.md
  trunk/as0006310/task_04/img/console-full-screen.png
  trunk/as0006310/task_04/img/console.png
  trunk/as0006310/task_04/readme.md
Labels: AS-63

#211 [task_05] Add task_05
  readme.md
  trunk/as0006310/task_05/images/monitor_done.png
  trunk/as0006310/task_05/readme.md
Labels: AS-63

#215 [task_02] Add task_02
  readme.md
  trunk/as0006433/task_02/doc/doxygen.md
  trunk/as0006433/task_02/doc/imgs/linearmodel.png
  trunk/as0006433/task_02/doc/imgs/nonlinearmodel.png
  trunk/as0006433/task_02/doc/readme.md
  trunk/as0006433/task_02/src/CMakeLists.txt
  trunk/as0006433/task_02/src/main.cpp
Labels: AS-64

#217 [task_03] Add lab
  readme.md
  trunk/as0006433/task_03/doc/imgs/1.png
  trunk/as0006433/task_03/doc/imgs/2.png
  trunk/as0006433/task_03/doc/imgs/3.png
  trunk/as0006433/task_03/doc/imgs/4.png
  trunk/as0006433/task_03/doc/imgs/5.png
  trunk/as0006433/task_03/doc/imgs/6.png
  trunk/as0006433/task_03/doc/imgs/7.png
  trunk/as0006433/task_03/doc/imgs/8.png
  trunk/as0006433/task_03/doc/imgs/9.png
  trunk/as0006433/task_03/doc/readme.md
Labels: AS-64

#218 [task_04] Add work
  readme.md
  trunk/as0006433/task_04/doc/imgs/1.png
  trunk/as0006433/task_04/doc/imgs/2.png
  trunk/as0006433/task_04/doc/imgs/3.png
  trunk/as0006433/task_04/doc/imgs/4.png
  trunk/as0006433/task_04/doc/imgs/5.png
  trunk/as0006433/task_04/doc/readme.md
Labels: AS-64

#219 [task_03] Add content
  readme.md
  trunk/as0006415/task_03/doc/pictures/1.png
  trunk/as0006415/task_03/doc/pictures/2.png
  trunk/as0006415/task_03/doc/pictures/3.png
  trunk/as0006415/task_03/doc/pictures/4.png
  trunk/as0006415/task_03/doc/pictures/5.png
  trunk/as0006415/task_03/doc/pictures/6.png
  trunk/as0006415/task_03/doc/readme.md
Labels: AS-64

#220 [task_04] Add content
  readme.md
  trunk/as0006415/task_04/doc/pictures/1.png
  trunk/as0006415/task_04/doc/pictures/2.png
  trunk/as0006415/task_04/doc/readme.md
Labels: AS-64

#221 [task_03] Add task
  readme.md
  trunk/as0006313/task_03/doc/README.md
  trunk/as0006313/task_03/doc/imgs/access_rights.png
  trunk/as0006313/task_03/doc/imgs/executable_file.png
  trunk/as0006313/task_03/doc/imgs/network_configuration.png
  trunk/as0006313/task_03/doc/imgs/output.png
  trunk/as0006313/task_03/doc/imgs/ping_controller.png
  trunk/as0006313/task_03/doc/imgs/putty.png
  trunk/as0006313/task_03/doc/imgs/putty_connection.png
  trunk/as0006313/task_03/doc/imgs/winscp.png
  trunk/as0006313/task_03/doc/imgs/winscp_connection.png
Labels: AS-63

#223 [task_04] Add content
  readme.md
  trunk/as0006313/task_04/doc/README.md
  trunk/as0006313/task_04/doc/imgs/access_rights.png
  trunk/as0006313/task_04/doc/imgs/create_directory.png
  trunk/as0006313/task_04/doc/imgs/executable_file.png
  trunk/as0006313/task_04/doc/imgs/laptop.jpg
  trunk/as0006313/task_04/doc/imgs/output.png
  trunk/as0006313/task_04/doc/imgs/winscp.png
Labels: AS-63

#222 [task_02] Add content
  readme.md
  trunk/as0006304/task_02/doc/README.md
  trunk/as0006304/task_02/doc/doxygen.md
  trunk/as0006304/task_02/doc/image/linear.png
  trunk/as0006304/task_02/doc/image/nonLinear.png
  trunk/as0006304/task_02/src/CMakeLists.txt
  trunk/as0006304/task_02/src/lab.cpp
Labels: AS-63

#224 [task_03] Add content
  readme.md
  trunk/as0006304/task_03/doc/README.md
Labels: AS-63

#225 [task_04] Add task 04
  readme.md
  trunk/as0006304/task_04/doc/README.md
  trunk/as0006304/task_04/doc/images/img_01.png
  trunk/as0006304/task_04/doc/images/img_02.png
Labels: AS-63
